language: scala

scala:
- 2.11.7

jdk:
- oraclejdk8
- openjdk6

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt ++${TRAVIS_SCALA_VERSION} test

sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7d9188983e70fdb9839f
